//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace solicitudescooitza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatRoles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatRoles()
        {
            this.TblUsuarios = new HashSet<TblUsuarios>();
        }
    
        public long idCatRoles { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblUsuarios> TblUsuarios { get; set; }
    }
}
